apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-local-pv
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
    type: DirectoryOrCreate
